// @flow
export default {
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  UPDATE_DATA: 'UPDATE_DATA',
  UPDATE_FAVORITE: 'UPDATE_FAVORITE',
}